### ISSUE TITLE
Unstable formatting for jinja config block

### ISSUE THREAD

**Issue by ryanmeekins** [tconbeer/sqlfmt#191]
**Describe the bug**
The formatter is unstable with dbt config blocks.

Likely related to  #175 but not sure.

**To Reproduce**
Start with a simple file with a config block definition, such as  [config_block.txt](https://github.com/tconbeer/sqlfmt/files/8834525/config_block.txt), and make a minor change. Run the formatter and then make another minor change and run the formatter again. You should see the indentation of the config variables increasing each time (4 more spaces).

**Expected behavior**
The formatter should produce a stable result.

**Actual behavior**
The formatter is unstable because it keeps indenting the config variables.

**Additional context**
sqlfmt, version 0.9.0

**Comment by tconbeer** [comment]
Thanks for the report!

This sounds more like #138 and #176 to me.

I have a few questions, since I can't reproduce: 

1. Did you install sqlfmt with the jinjafmt extra? (`pip install sqlfmt[jinjafmt]`) and/or do you otherwise have [black](https://github.com/psf/black) installed?
2. Does this still happen if you run sqlfmt with the `--no-jinjafmt` option? e.g., `sqlfmt --no-jinjafmt myfile.sql`?
3. Rather than making small changes to your file, can you reproduce if you pass the `-k` option to sqlfmt? This clears the cache and forces reformatting, even if the source file is unchanged. `sqlfmt -k myfile.sql`

**Comment by ryanmeekins** [comment]
Sorry, this was an issue with the version specified in my pre-commit hook (forgot that pre-commit had it's own config and it was using `v0.5.1`). Realized this after just using the `sqlfmt` command directly.

Thanks for the quick response and for providing the different commands that will be helpful to my team in the future. Keep up the great work!

**Comment by tconbeer** [comment]
Ah yes, I wish there was a better way to keep pre-commit in sync with other dependencies. Thanks for using sqlfmt!
