### ISSUE TITLE
Psycopg placeholders

### ISSUE THREAD

**Issue by snorkysnark** [tconbeer/sqlfmt#198]
**Describe the bug**
sqlfmt breaks placeholders used by [psycopg](https://www.psycopg.org/) (python postgres driver), such as `%s` and `%(name)s`

**To Reproduce**
Format the following code:
```sql
INSERT INTO some_table VALUES (%s)
```
```sql
INSERT INTO some_table VALUES (%(foo)s)
```

**Expected behavior**
The placeholders should remain intact:
```sql
insert into some_table values(%s)
```
```sql
insert into some_table values(%(foo)s)
```

**Actual behavior**
sqlfmt inserts extra spaces:
```sql
insert into some_table values(% s)
```
```sql
insert into some_table values(% (foo) s)
```

**Additional context**
What is the output of `sqlfmt --version`?
`sqlfmt, version 0.9.0`

**Comment by snorkysnark** [comment]
Yes, they behave similarly in select statements

Here's the relevant documentstion for psycopg2 and psycopg3:
https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries
https://www.psycopg.org/psycopg3/docs/basic/params.html

**Comment by tconbeer** [comment]
Thanks for the docs! I love how explicit they are on the format for these placeholders; should make lexing them quite straightforward.

Any interest in contributing  the fix for this? Should be quite straightforward. You can use this PR as a guide (it added support for `$1` and `@my_stage` as other identifiers): https://github.com/tconbeer/sqlfmt/pull/126

The steps would be:
1. create a new Rule (in dialect.py) with a regex for matching these placeholders and creating a `NAME` token
2. make sure the new Rule's priority is lower than the operator rule
3. modify the operator rule to match `%%` (the escaped mod operator in a psycopg string)
4. add tests in `test_dialect.py` and add a new file to `test_general_formatting.py`
