### ISSUE TITLE
Issue with jinja call and endcall syntax with v0.14.0

### ISSUE THREAD

**Issue by AndrewLane** [tconbeer/sqlfmt#335]
**Describe the bug**
sqlfmt error with jinja syntax for start and endcall that used to parse previously.

**To Reproduce**
Run sql-fmt on the following code:

```
{% call dbt_unit_testing.mock_ref('some_table') %}
id | foo
1 | 2022
{% endcall %}

```

**Expected behavior**
Should not fail to parse

**Actual behavior**
```
sqlfmt encountered an error: Encountered closing bracket '{% endcall %}' at position xxx, before matching opening bracket. Context: {% endcall %}
```
**Additional context**
Version v0.14.0 appears to break this

**Comment by AndrewLane** [comment]
And an even more simple example fails as well:

```
{% call foo() %}
select * from foo
{% endcall %}
```

**Comment by tconbeer** [comment]
ok, I see the problem... I thought in dbt, the call blocks have to be labeled `{% call statement(...) %}` or `{% call noop_statement(...) %}` -- it seems the package is creating new jinja macros called `mock_ref`, etc., and calling those with the `call` syntax? I actually didn't realize that was possible. Are these equivalent?

```sql
{% set args %}
select * from foo
{% endset %}
{{ foo(args) }}
```

The reason I ask is because for `call statement` blocks, I know the contents have to be SQL, but for arbitrary `set` or `call` blocks, they can be data (as in your original example), so we'd need to skip formatting them entirely

**Comment by AndrewLane** [comment]
@tconbeer Thanks!  Will look for a new version with this change and try it out...
